server:
  port: 8085
spring:
 
        
 
  datasource:
    password: Kiran*123#
    url: jdbc:mysql://localhost:3306/projects
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    
